version: "3.5"

services:

  openethereum-client:
    build:
      context: .
    volumes:
      - /var/data/ssd/openethereum:/home/dockeruser/openethereum
      - ./config.toml:/home/dockeruser/.local/share/io.parity.ethereum/config.toml
    networks:
      - graphsense-net
    ports:
      - 192.168.243.2:18545:8545
      - 33303:30303
    restart: always

networks:
  graphsense-net:
    name: graphsense-global-net
