services:
  erigon:
    image: erigontech/erigon:v3.0.15
    #user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    ports:
      - "8545:8545"
    volumes:
      - ${DATA_HOME}:/home/erigon/.local/share/erigon
    command: >
      --chain=mainnet
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=eth,net,web3,debug,trace
      --http.vhosts *
      --prune.mode=archive
