version: "3.5"

services:

  openethereum-client:
    build:
      context: .
    volumes:
      - ./data:/home/dockeruser/openethereum
      - ./config.toml:/home/dockeruser/.local/share/io.parity.ethereum/config.toml
    networks:
      - graphsense-net
    ports:
      - 8545:8545
      - 30303:30303
    restart: always

networks:
  graphsense-net:
    name: graphsense-global-net
